First version.
linuxdeploy/libelfutil pull request #1
Opened 2018-10-17 22:17 UTC by azubieta

2018-10-18 07:02 UTC, TheAssassin requested changes
It doesn't make any sense to manage one half of the dependencies using submodules, the other one using this DownloadProject script. Please switch everything to submodules.

As in many of your PRs, there's lots of files lacking a trailing newline character. The GitHub browser reveals that. Please either take care of it manually, or find a technical way to automate this (IDEs usually have an option for that).

2018-10-18 07:02 UTC, TheAssassin commented on include/elfutil/ElfFile.h
> +// system includes
I'd prefer lower case public header filenames, like the rest of the world uses them (except Qt, maybe).

2018-10-18 07:02 UTC, TheAssassin commented on include/elfutil/errors.h
> +}
Missing trailing newline.

2018-10-18 07:02 UTC, TheAssassin commented on src/CMakeLists.txt
> +    elfutil/errors.cpp)
```
add_library(elfutil SHARED
￼     elfutil/ElfFile.cpp
￼     elfutil/log.cpp
￼     elfutil/errors.cpp
)
```

2018-10-18 07:02 UTC, TheAssassin commented on src/CMakeLists.txt
> +    )
```suggestion
)
```

2018-10-18 07:02 UTC, TheAssassin commented on src/CMakeLists.txt
> +    PUBLIC_HEADER
Please use a single line.

2018-10-18 07:02 UTC, TheAssassin commented on src/CMakeLists.txt
> +    VERSION ${libelfutil_VERSION} SOVERSION ${libelfutil_VERSION_MAJOR}
Is `SOVERSION` standard? Do we have to introduce that elsewhere? From which version of CMake is it available?

2018-10-18 07:02 UTC, TheAssassin commented on src/CMakeLists.txt
> +    PUBLIC_HEADER DESTINATION "${INSTALL_INCLUDE_DIR}/elfutil" COMPONENT dev)
```
install(
    TARGETS elfutil
￼    EXPORT ElfUtilTargets
￼    LIBRARY DESTINATION "${INSTALL_LIB_DIR}" COMPONENT lib
￼    PUBLIC_HEADER DESTINATION "${INSTALL_INCLUDE_DIR}/elfutil" COMPONENT dev
)

2018-10-18 07:02 UTC, TheAssassin commented on src/elfutil/errors.cpp
> +}
Missing trailing newline.

2018-10-18 07:02 UTC, TheAssassin commented on src/elfutil/log.cpp
> +}
I guess we don't need a copy of linuxdeploy's entire logging module in here. In fact, I'd remove any sort of logging from the library (except for debugging, maybe, but something simpler should do for that purpose).

2018-10-18 07:02 UTC, TheAssassin commented on src/elfutil/misc.hpp
> +}
We don't need half of these methods. Please remove anything we don't need.

2018-10-18 07:02 UTC, TheAssassin commented on tests/simple_library/CMakeLists.txt
> +target_link_libraries(simple_library)
Missing trailing newline.

2018-10-18 23:13 UTC, azubieta commented on src/elfutil/log.cpp
> +}
I'll create an issue for this.

2018-10-18 23:23 UTC, azubieta commented on src/CMakeLists.txt
> +    VERSION ${libelfutil_VERSION} SOVERSION ${libelfutil_VERSION_MAJOR}
https://cmake.org/cmake/help/v3.0/prop_tgt/SOVERSION.html

2018-10-19 00:25 UTC, azubieta commented
All issues fixed, proceeding to merge.

2018-10-19 00:27 UTC, merged